package dev.dna.deliveryapp.navigation

enum class ScreenRoutes {
    SPLASH,
    LOGIN,
    REGISTER,
    OTP_CODE,
    HOME,
    FOOD,
    ANYTHING,
    FASHION,
    ELECTRONICS,
    PACKAGE_DELIVERY,
    HEALTH_AND_BEAUTY,
    USER_PROFILE,
    CART,
    FOOD_OR_PRODUCT_ITEM,
    STORE_OR_SHOP,
    SELECTED_FOOD_AND_PROMO,
    CHECK_OUT_AND_NUMBER,
    DROP_OFF_OPTIONS,
    USER_INFORMATION,
    DELIVERY_LOCATION_MAP,
    WELCOME,
    PHONE_NUMBER,
    ORDERS,
    SEARCH_LOCATION,
    LOCATION_MAP;
}